### ISSUE TITLE
Add some space between every items in all the cards

### ISSUE THREAD

**Issue by lokeswaran-aj** [Swetrix/roadmap#119]
I would like to see some margin space between every item in the dashboard cards.

Eg: Space between every link in the Referrer or make the text smaller.
<img width="491" alt="Screenshot 2023-02-06 at 1 46 13 PM" src="https://user-images.githubusercontent.com/74011196/216919490-2b1a9901-24fe-4631-bfde-63c4207a90fd.png">

**Comment by Blaumaus** [comment]
added in https://github.com/Swetrix/swetrix-fe/commit/da319d588944f9f81dfa1a0d14fd57992e914d8f
