### ISSUE TITLE
Migrate the transactional DB from MySQL to PostgreSQL

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#128]

**Comment by yevheniikulisidi** [comment]
You can also additionally migrate from TypeORM to Prisma and completely rewrite the code of functions with database queries through Prisma ORM.

**Comment by Blaumaus** [comment]
Closing it for now as this task is not a priority and current MySQL set up works well.

**Comment by kulogix** [comment]
PostgreSQL support would be appreciated to allow for more distributed/scalable deployment using CockroachDB and all it has to offer (particularly around keeping user data within specific countries/data centers).
