### ISSUE TITLE
Update Marketplace obsolete Dashboard to match Swetrix dashboard

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#157]

**Comment by ArtemRozzhivin** [comment]
#Update Marketplace obsolete Dashboard to match Swetrix dashboard #157 #64

**Comment by ArtemRozzhivin** [comment]
Update Marketplace obsolete Dashboard to match Swetrix dashboard #157 #64
 - https://github.com/Swetrix/marketplace-fe/pull/64
