### ISSUE TITLE
Add log-out from all devices feature

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#160]
Under the user settings, there should be a button 'Log out from all other devices' (or something similar) - that when clicked on will erase all the refresh tokens for this specific account from the database (except the currently used one).

**Comment by kruzhambus** [comment]
https://github.com/Swetrix/swetrix-api/pull/157

**Comment by Blaumaus** [comment]
API: https://github.com/Swetrix/swetrix-api/pull/155
FE: https://github.com/Swetrix/swetrix-fe/pull/310
