### ISSUE TITLE
Improve account deletion process

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#161]
When user deletes an account - it should be verified by entering their password.

Ideally, the accounts should be 'soft deleted' first in case user changes his mind. The 'hard deletion' should occur after some threshold (for example, 5 days).

It also would be good to collect feedback as to **why** do users want to delete their account.
It should be either a simple message in the account deletion modal like 'Please tell us why do you want to delete your account, you can do so at our [contact page].' or preferably an input field (in the account deletion modal) where user can enter the feedback directly (the feedback can be stored in a dedicated table in the database or maybe sent to Telegram).

**Comment by Pranavvks** [comment]
Hi @Blaumaus. 

Sorry, I couldn’t work on the issue that was assigned to me earlier. I got a bit busy with university and faced an injury at the gym.

Could you please let me know if there are any good first issues available that I can work on ?.
