### ISSUE TITLE
Plan limit usage notification improvements

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#167]
- [ ] Add customisations to the plan limit usage notification. I.e. let the user choose at which % of plan used they'll get a notifications (a dropdown, where they'll be able to pick values from 10% to 100%).
- [ ] If user has a messenger (e.g. Telegram) connected to their Swetrix account - notification should be sent there as well.

**Comment by alceil** [comment]
Can I work on this @Blaumaus

**Comment by kruzhambus** [comment]
@alceil Hi, how are you doing with this issue? Do you have any questions or need help?

**Comment by alceil** [comment]
I was waiting for this issue to be assigned to me @kruzhambus 😅 Anyways I will start working on it soon

**Comment by alceil** [comment]
Thanks @kruzhambus

**Comment by kruzhambus** [comment]
@alceil Thank you too, we are looking forward to your pull request)

**Comment by alceil** [comment]
Can I get some help on how to deploy the project locally for development I cant see about it on the docs @kruzhambus

**Comment by kruzhambus** [comment]
Okay it’s a link for our discord [https://discord.gg/TkQSTFYE](https://discord.gg/TkQSTFYE) 
but I'm a little busy right now and will be able to help you in 30 minutes to an hour

**Comment by alceil** [comment]
Sure @kruzhambus

**Comment by Pranavvks** [comment]
I would like to work on this issue @Blaumaus.

**Comment by Borfak** [comment]
https://github.com/Swetrix/swetrix-api/pull/211

**Comment by Blaumaus** [comment]
API: https://github.com/Swetrix/swetrix-api/pull/211
FE: https://github.com/Swetrix/swetrix-fe/pull/391
