### ISSUE TITLE
Raw data exports

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#24]
**Brief description:**
Add ability for users to export raw data related to projects.

**Detailed description:**
As the data belongs to users, we should add an ability to export raw data from the database, not only JSON / CSV / etc. aggregated data exports.
The exported data should contain a CSV tables (custom events / performance / analytics) of all the events per a specific project per a specific timeframe.

The CSV tables should be archived (.zip) and uploaded to Swetrix CDN.
After that the user can download his data archive by opening the link which will be available in the project settings (?) AND sent to their email address.

[!] The download link should expire after 48 hours and the archive has to be deleted from Swetrix CDN.

**Bonus points for the following:**
Preferably, the download should only be available when user is authenticated in his account, so the 3rd party who has access to their email wouldn't be able to access the archive.
IMO this can be done via the following:
frontend -> api <-> cdn

where:
user opens a dedicated `frontend` page (e.g. https://swetrix.com/project/xxxxxxxxx/exportId), the request is made to a protected API endpoint. In case the user is authed and has access to the project, API returns the CDN link and the download is automatically started afterwards.

**Comment by yevheniikulisidi** [comment]
Can a user with the role of admin create and export raw user project data?

**Comment by kruzhambus** [comment]
Yes

**Comment by yevheniikulisidi** [comment]
When exporting raw data, is it necessary to specify a certain period of time?

**Comment by yevheniikulisidi** [comment]
Can an invited user in a project with the role of administrator create and export raw project data?

**Comment by kruzhambus** [comment]
Yes,please go to see old messages

**Comment by pro1code1hack** [comment]
@kruzhambus  what is the status for this task? Can I pick it up? I saw 2 closed MRs, what's the issue with them?

**Comment by Blaumaus** [comment]
Closing as "Not planned" for now
