### ISSUE TITLE
Migrate frontend from React to SSR

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#3]
It would be great to migrate from Client to Server side rendering.
Currently, many search engines are not capable to correctly crawl React applications, thus it's a huge disadvantage from the SEO point of view.
Also as we support multiple languages, client side rendering simply does not support displaying content in multiple languages to the search engines painlessly..

Probably, we will migrate the frontend to Gatsby, which looks perfect for this usecase.

**Comment by hughbris** [comment]
I'm generally supportive of SSR wherever practical and I have just come poking around for issues before trying Swetrix for the first time...

I'm just curious: why is SEO important for an analytics dashboard? I would put a `robots disallow` on that.

**Comment by Blaumaus** [comment]
> I'm generally supportive of SSR wherever practical and I have just come poking around for issues before trying Swetrix for the first time...
> 
> I'm just curious: why is SEO important for an analytics dashboard? I would put a `robots disallow` on that.

We're almost done migrating to SSR (Remix Framework).

Generally it offers a lot of benefits, for example JS is no longer mandatory to open the website as it's rendered on the server, performance improvements, huge SEO improvements (each page would have it's title / description / etc. set in the HTML, we'll be able to return 404 status code in case user opens a page that does not exist (currently React returns 200 status code to any page)), an ability to generate custom image previews per project (for example, when you share a link to your Project Dashboard on Twitter we'll be able to provide it with a beautiful, custom preview image that may contain, for instance, your stats for the previous week).

**Comment by hughbris** [comment]
> currently React returns 200 status code to any page

I hope someone is serving a jail term for this :/
