### ISSUE TITLE
[idea] Add a quick summary

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#50]
Not sure if it's needed, but definetely worth to discuss.

**Task:**
Add a quick summary block with some general information about the selected period.
![image](https://user-images.githubusercontent.com/35810911/173164146-30864a67-8ef2-4d82-a8b1-567cf8610891.png)

**Comment by kruzhambus** [comment]
I think today we don't need it anymore because the dashboard is already overflowing
