### ISSUE TITLE
Optional pie chart on the 'Browser', 'OS' and 'Device' blocks

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#51]
**Task**
Optional pie charts have to be added to 'Browser', 'OS' and 'Device' blocks.

**Approximate UI**
![swe](https://user-images.githubusercontent.com/35810911/173164794-616467c8-c498-4319-a665-342e49adf3c0.png)

**Comment by kruzhambus** [comment]
https://github.com/Swetrix/swetrix-fe/pull/74
