### ISSUE TITLE
Email hard-bounces / unsubscribes

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#55]
<img width="1421" alt="Screenshot 2022-07-27 at 0 38 43" src="https://user-images.githubusercontent.com/35810911/181117470-0d2ad799-73e6-46a1-9cf7-93a53fad2f87.png">

The hard bounces / unsubscribed related issues should be catched this try/catch on the mail sender service.
In case if the email is `broadcast` and related to things like email reports, the email report frequency should be set to `Never` for such user.

**Описание:**
Функция, которая крашится, называется `sendEmail` и находится в src -> mailer -> mailer.service.ts.
Крашится код `await mailClient.sendEmail(message)` (119 строка).

**Что нужно сделать:**
Засунуть `await mailClient.sendEmail(message)` в `try / catch`, в catch (в случае когда будет ошибка) нам нужно сделать следующее:
добавить блок `if` и в нём проверять, не является ли `statusCode` ошибки 422:
 - если ошибка не 422, нужно в консоль вывести следующее: `console.error(`[ERROR][MAILER] ${e}`)`;
 - если ошибка 422, то необходимо проверить, является ли переменная `messageStream` === `broadcast`:
   - если false - по аналогии с кодом выше выводим ошибку в консоль;
   - если true - в user entity в поле `reportFrequency` нужно записать значение из enum ReportFrequency.Never (находится в src -> user -> entities -> user.entity.ts).
     Тут будет небольшая проблемка чтобы из модуля mailer это записать в базу данных, так что может реализуй это через колбек (если что, уточнишь у Макса или у меня).

**Comment by rhaxma** [comment]
It was done in this PR - https://github.com/Swetrix/swetrix-api/pull/28
