### ISSUE TITLE
An ability to add administration tags to the extension

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#71]
**Acceptance criteria:**
It should be possible to add permanent tags to extensions in the admin panel.
For example tags such as 'Editors choice', 'Recommended'.
Users should not be able to add these tags themselves.

There should also be functionality to automatically add and remove the following tags:
- 'New': a tag that is automatically added to all extensions when they are created and removed after 2 weeks;
- 'Trending': a tag which is automatically added to the extension when it gets a huge amount of installations and when the amount of installations exceeds a certain percentage of the other extensions in the marketplace. This tag should be removed automatically if the number of installs in the last 2 weeks is less than the number of installs in the 2 weeks before that.
For example: 
  - For the last 2 weeks extension had 300% more installs then before, the amount of installs is > than the amount of installs for the 90% of other extensions on the marketplace -> the 'Trending' tag is automatically granted to the extension.
  - For the last 2 weeks extension had 100 installs, 2 weeks before that it had 80 -> the extension keeps the 'Trending' tag.
  - For the last 2 weeks extension had 100 installs, 2 weeks before that it had 140 -> the 'Trending' tag gets removed.

**Comment by kruzhambus** [comment]
https://github.com/Swetrix/marketplace-fe
