### ISSUE TITLE
Ability to accept or reject extensions

### ISSUE THREAD

**Issue by R0YV0VA** [Swetrix/roadmap#76]
Admin must have a name, description and extension file. After review, admin clicks on the accept or reject button.
The admin should also have a field to write a description of his decision.
If he clicks accept the status in the DB will changed and letter will be sent to the email.
If he clicks reject the file with the extension and the row in DB are deleted, and a letter is sent to the email with the reason for rejection.

**Comment by kruzhambus** [comment]
https://github.com/Swetrix/new-admin-panel/pull/13
