### ISSUE TITLE
Extension load and execution for projects at swetrix.com

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#78]
_THIS SECTION IS YET TO BE DISCUSSED AND COMPLETED_

When user installs the extension from Swetrix Marketplace, it has 2 installation options:
1. Install the extension to a specific project.
2. Install the extension globally and getting run on each users' project.

The when publishing the extensions, they will be stored in a separate table, each having a unique identifier.
When user installs the extension, this identifier will be appended to the array of installed extensions in the database (there will be 2 new rows named `extensions` in the project table and users table (for global installations)).
When user opens Swetrix, all these extensions (.js files) are loaded from the CDN by their unique IDs (the uuid's will match extension .js name).
**The extensions can only be executed on the project view screen.**
**The extensions can never, ever access data related to the user, it's email, or any other personal info or settings.**

As for now, there are 3 kinds of extensions:
1. Data visualisation (i.e. you can see data in different charts in panel, as a map, or whatever the extension can offer).
2. Data exports in a different formats the extension offers.
3. (currently not supported) Separate tabs where extensions can render their own layouts based on the analytics data.

The user should always be able to easily disable installed extensions, or move them from globally installed to project specific and vice versa.

**Comment by pro1code1hack** [comment]
Omagad, i would suck to the owner of this project!

**Comment by Blaumaus** [comment]
Done:
https://github.com/Swetrix/extensions-sdk
https://github.com/Swetrix/swetrix-fe/pull/153
