### ISSUE TITLE
Add ability to delete project data via filters

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#8]
**Brief description:**
For example, let user delete the project's data for a specific day (or a date rage), or delete the analytics data with some specific referrer, country of origin, etc.

**Detailed description:**
Additionally to being able to delete whole project (and it's data) from the database, the user should be able to remove the project data partially (for example, if their website is raided by bots or they want to free up some space in their tier).

**Comment by kruzhambus** [comment]
Already done for deleting the project data for a date range or day
