### ISSUE TITLE
Added filter for custom events

### ISSUE THREAD

**Issue by kruzhambus** [Swetrix/roadmap#86]
Added filter to this panel
![Screenshot from 2022-08-11 00-00-33](https://user-images.githubusercontent.com/80621719/184019613-45b785ff-af34-4777-b6b0-5a6928b01a1c.png)

**Comment by Blaumaus** [comment]
https://github.com/Swetrix/swetrix-js/pull/4
https://github.com/Swetrix/swetrix-api/pull/99
