### ISSUE TITLE
Soring filters in the page URL

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#96]
_I want to filter a specific page and share a direct link with users so they can see their prfile page stats. Other pages should be hidden completely.  I want people to see, what page I share with them. not others.  Example: domain.com/Amy domain.com/Alex domain.com/Mike  If so  https://app.umami.is/share/8rmHaheU/umami.is?view=url&url=%2Fmike  I don't want Any and Alex see Mike's stats or whole stats.  Did you understand?_

**Comment by Amit-Biswas** [comment]
This request was mine. Thank you so much for implementing this function. 

Thanks again,
~ Amit
