### ISSUE TITLE
Storing timeframe & time bucket in the page URL

### ISSUE THREAD

**Issue by Blaumaus** [Swetrix/roadmap#97]
Similarly to https://github.com/Swetrix/roadmap/issues/96 we should provide a feature to store timeframe & time bucket in the page URL.
<img width="351" alt="Screenshot 2022-09-05 at 2 29 13" src="https://user-images.githubusercontent.com/35810911/188337631-5f1231ba-b04a-448b-aa33-c3cc53764729.png">

**Comment by kruzhambus** [comment]
pull request: https://github.com/Swetrix/swetrix-fe/pull/139
